services:
  latex:
    # コンテナ名
    container_name: ${CONTAINER_NAME}
    # Dockerfileへのパス
    build:
      context: .
      args:
        - USER_UID=${UID:-1000}
        - USER_GID=${GID:-1000}
    # ビルドされたイメージのタグ
    image: ${HOST_NAME}/${SERVICE_NAME}:${VERSION}
    # ボリュームマウント
    volumes:
      - ./src:/home/texlive/src
      - ./.vscode-server:/home/texlive/.vscode-server
    command: >
      bash
    tty: true